name = "Ashokai Urple"
author = "TeriyakiBomb"
version = "1.0.0"

# Syntax highlighting
"type" = "purple"
"constant" = "magenta"
"constant.numeric" = "magenta"
"constant.character.escape" = "orange"
"string" = "orange"
"string.regexp" = "blue0"
"comment" = "comment"
"variable" = "yellow"
"class" = {fg ="purple", modifiers = ["bold"]}
"variable.builtin" = "blue0"
"variable.parameter" = "yellow"
"variable.other.member" = "fg0"
"label" = "purple"
"punctuation" = "grey1"
"punctuation.delimiter" = "lightblue"
"punctuation.bracket" = "blue1"
"keyword" = "blue0"
"keyword.directive" = "aqua"
"operator" = "lightblue"
"function" = "green"
"function.builtin" = "blue0"
"function.macro" = "aqua"
"tag" = "magenta"
"namespace" = "aqua"
"attribute" = "green"
"constructor" = "purple"
"module" = "blue0"
"special" = "orange"
"variable.instance_variable" = "magenta"

# Markup
"markup.heading.marker" = "grey1"
"markup.heading.1" = { fg = "purple", modifiers = ["bold"] }
"markup.heading.2" = { fg = "magenta", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue0", modifiers = ["bold"] }
"markup.heading.6" = { fg = "fg0", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue0", modifiers = ["underlined"] }
"markup.link.text" = "magenta"
"markup.quote" = "grey1"
"markup.raw" = "green"

# Diff
"diff.plus" = "diffgreen"
"diff.delta" = "orange"
"diff.minus" = "red"

# UI elements
"ui.background" = { bg = "bg0" }
"ui.background.separator" = "grey0"

"ui.cursor" = { fg = "bg0", bg = "cursor" }
"ui.cursor.match" = { fg = "orange", bg = "bg_visual_yellow" }
"ui.cursor.insert" = { fg = "bg0", bg = "grey1" }
"ui.cursor.select" = { fg = "bg0", bg = "blue0" }
"ui.cursor.primary" = {fg = "bg0", bg ="fg0"}
"ui.cursor.primary.normal" = {fg = "bg0", bg ="fg0"}
"ui.cursorline.primary" = { bg = "cursorline" }
"ui.cursorline.secondary" = { bg = "cursorline" }

"ui.selection" = { bg = "cursorline" }
"ui.selection.primary" = { bg = "bg2" }
"ui.linenr" = "line_number"
"ui.linenr.selected" = "line_number_selected"
"ui.statusline" = { fg = "fg0", bg = "bg3" }
"ui.statusline.inactive" = { fg = "grey0", bg = "bg0" }
"ui.statusline.normal" = { fg = "bg0", bg = "fg0", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg0", bg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg0", bg = "pink", modifiers = ["bold"] }
"ui.bufferline" = { fg = "grey0", bg = "bg1" }
"ui.bufferline.active" = { fg = "fg0", bg = "bg3", modifiers = ["bold"] }
"ui.popup" = { fg = "grey1", bg = "bg2" }
"ui.window" = { fg = "grey0", bg = "bg0" }
"ui.help" = { fg = "helptext", bg = "helpbg" }
"ui.text" = "fg0"
"ui.text.focus" = "fg0"
"ui.menu" = { fg = "fg0", bg = "bg3" }
"ui.menu.selected" = { fg = "bg0", bg = "blue0", modifiers = ["bold"] }
"ui.virtual.whitespace" = { fg = "bg3" }
"ui.virtual.indent-guide" = { fg = "bg3" }
"ui.virtual.ruler" = { bg = "bg3" }

# Diagnostics
"hint" = "blue0"
"info" = "aqua"
"warning" = "yellow"
"error" = "red"
"diagnostic" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue0", style = "dotted" } }
"diagnostic.info" = { underline = { color = "aqua", style = "dotted" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

[palette]
bg0 = "#211D2A"
bg1 = "#322750"
bg2 = "#49385D"
bg3 = "#4B3E64"
fg0 = "#EFEAFF"
helptext="#9485b9"
helpbg="#130F1C"
grey = "#70697D"
grey1 = "#667E99"
red = "#FF5D5D"
yellow = "#FBC664"
green = "#7AEA92"
blue = "#7AC3FF"
blue1 = "#4E6A97"
lightblue = "#B0DDD2"
aqua = "#5DB1B1"
orange = "#FF9647"
purple = "#9983D7"
magenta = "#F94786"
pink = "#E06798"

diffgreen = "#5B7753"

line_number = "#5D5E72"
line_number_selected = "#7262A6E"
comment =  "#565775"

cursor = "#746F7F"
cursorline = "#2B2437"
